name: Deploy dbt
on:
 schedule:
    - cron: 0 4 * * *
env:
  DB_HOST: '${{ secrets.DB_HOST }}'
  DB_PORT: '${{ secrets.DB_PORT }}'
  DB_USER: '${{ secrets.DB_USER }}'
  DB_PASS: '${{ secrets.DB_PASS }}'
  DB_NAME: '${{ secrets.DB_NAME }}'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@masterbranch
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install dbt
          dbt deps --target {{target}}
      - name: Run dbt
        run: |
          dbt run --target {{target}}
      - name: Test using dbt 
          dbt test --target {{target}'
